/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tigerknows_map_Ca */

#ifndef _Included_com_tigerknows_map_Ca
#define _Included_com_tigerknows_map_Ca
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tigerknows_map_Ca
 * Method:    a
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_a
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    b
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tigerknows_map_Ca_b
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ba
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tigerknows_map_Ca_ba
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    bb
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_tigerknows_map_Ca_bb
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ca
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_tigerknows_map_Ca_ca
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    c
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_c
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    d
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tigerknows_map_Ca_d
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    e
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_e
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    f
 * Signature: ()[Lcom/tigerknows/map/TileDownload;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tigerknows_map_Ca_f
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    g
 * Signature: (III)[Lcom/tigerknows/map/label/Label;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tigerknows_map_Ca_g
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    h
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_h
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    i
 * Signature: (DI)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_i
  (JNIEnv *, jclass, jdouble, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    j
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_j
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    k
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_k
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    l
 * Signature: (III[B)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_l
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    m
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tigerknows_map_Ca_m
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    n
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_n
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    o
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tigerknows_map_Ca_o
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    aa
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_aa
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ab
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tigerknows_map_Ca_ab
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ac
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tigerknows_map_Ca_ac
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ad
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tigerknows_map_Ca_ad
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ae
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tigerknows_map_Ca_ae
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    af
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tigerknows_map_Ca_af
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ag
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tigerknows_map_Ca_ag
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ah
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_tigerknows_map_Ca_ah
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ai
 * Signature: (DD)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tigerknows_map_Ca_ai
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    aj
 * Signature: (DDI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tigerknows_map_Ca_aj
  (JNIEnv *, jclass, jdouble, jdouble, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    ak
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_ak
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    al
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_al
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    am
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tigerknows_map_Ca_am
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    an
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tigerknows_map_Ca_an
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    p
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_p
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    q
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_q
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    r
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_r
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    s
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tigerknows_map_Ca_s
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    t
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tigerknows_map_Ca_t
  (JNIEnv *, jclass);

/*
 * Class:     com_tigerknows_map_Ca
 * Method:    u
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_tigerknows_map_Ca_u
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
